# Theme-specific config
---
name: ForeverDev
url: https://github.com/dmitriy-korotayev/hexo-theme-ForeverDev

favicon: /img/favicon.svg

# Analytics
google_analytics: G-FW8PJEJBF7
google_tag_manager: GTM-5FMVDS82

# Comments
disqus: TODO_disqus_shortname

sass:
  file: scss/style.scss
  sourceMap: true
  outFile: scss/style.css
  outputStyle: compressed
  includePaths:
    - node_modules
