# Theme-specific config
---
name: ForeverDev
url: https://github.com/dmitriy-korotayev/hexo-theme-ForeverDev

favicon: /img/favicon.svg

# Analytics
google_analytics: TODO

# Comments
disqus: TODOdisqus_shortname

sass:
  file: scss/style.scss
  sourceMap: true
  outFile: scss/style.css
  outputStyle: compressed
  includePaths:
    - node_modules
