name: ForeverDev
url: https://github.com/dmitriy-korotayev/hexo-theme-ForeverDev
favicon: /favicon.svg
logo: /logo.svg

# Disqus shortname (TODO)
disqus:
# Analytics (TODO)
google_analytics:
# Copyright Information (TODO)
copyright:
  since:
  name:
  url:
