---
env:
  browser: true
  commonjs: true
  es6: true
  node: false
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  semi: ["error", "never"]
  quotes: ["error", "single"]
  indent: ["error", 2]
  no-console: "warn"
